### ISSUE TITLE
FlushChunks doesn't seen to work with JSON version of the stats-webpack-plugin

### ISSUE THREAD

**Issue by BernardoS** [faceyspacey/webpack-flush-chunks#24]
I've seen in the boilerplates that the way to have access to the stats in production is by producing a JSON version of it with the `stats-webpack-plugin`.
```js
// in the webpack plugins
new StatsWriterPlugin({filename: 'stats/web.json'})
```
 I produced this `stats.json`
```json
{
  "assetsByChunkName": {
    "vendors": [
      "assets/js/vendors.js",
      "assets/js/vendors.js.map"
    ],
    "app": [
      "assets/js/app.js",
      "assets/css/app.css",
      "assets/css/style.css",
      "assets/js/app.js.map",
      "assets/css/app.css.map",
      "assets/css/style.css.map"
    ],
    "Sensors": [
      "assets/js/chunks/Sensors.js",
      "assets/js/chunks/Sensors.js.map"
    ],
    "Sensor": [
      "assets/js/chunks/Sensor.js",
      "assets/js/chunks/Sensor.js.map"
    ],
    "Notifications": [
      "assets/js/chunks/Notifications.js",
      "assets/js/chunks/Notifications.js.map"
    ],
    "Alerts": [
      "assets/js/chunks/Alerts.js",
      "assets/js/chunks/Alerts.js.map"
    ],
    "commons": [
      "assets/js/chunks/commons.js",
      "assets/js/chunks/commons.js.map"
    ],
    "manifest": [
      "assets/js/manifest.js",
      "assets/js/manifest.js.map"
    ]
  }
}
```
and eventually in my server side application I'll be calling:
```js
// chunkNames = ['Sensor']
const stats = require('./stats.json')
const {js, styles} = flushChunks(stats, {chunkNames, before: ['manifest'], after: ['app']})
```

But unfortunatelly I'm receiving this Error, which points out to the line of code where I call `flushChunks` in the end.
```log
TypeError: Cannot read property 'replace' of undefined at exports.default (C:\Users\bernardosunderhus\Desktop\pextra\node_modules\webpack-flush-chunks\dist\createApiWithCss.js:23:36) at flushChunks (C:\Users\bernardosunderhus\Desktop\pextra\node_modules\webpack-flush-chunks\dist\flushChunks.js:43:41) at exports.default (C:\Users\bernardosunderhus\Desktop\pextra\node_modules\webpack-flush-chunks\dist\flushChunks.js:29:10) at _callee$ (C:/Users/bernardosunderhus/Desktop/pextra/server/application/index.js:19:37) at tryCatch (C:\Users\bernardosunderhus\Desktop\pextra\node_modules\regenerator-runtime\runtime.js:65:40) at Generator.invoke [as _invoke] (C:\Users\bernardosunderhus\Desktop\pextra\node_modules\regenerator-runtime\runtime.js:303:22) at Generator.prototype.(anonymous function) [as next] (C:\Users\bernardosunderhus\Desktop\pextra\node_modules\regenerator-runtime\runtime.js:117:21) at step (C:\Users\bernardosunderhus\Desktop\pextra\server\application\index.js:26:191) at C:\Users\bernardosunderhus\Desktop\pextra\server\application\index.js:26:361
```

I'm currently using `webpack-flush-chunks@1.1.23`

**Comment by BernardoS** [comment]
Solving my own issue:
Apparently `webpack-flush-chunks` uses more than just the `assetsByChunkName` attribute, and since new releases of the `stats-webpack-plugin` the default is to emit the stats file only with this `assetsByChunkName` attribute, so to solve this issue you baically have to add the `publicPath` attribute, since it is also used by the `webpack-flush-chunks`
```js
// in your webpack plugin config
new StatsWriterPlugin({
    filename: 'stats.json',
    fields: ['assetsByChunkName', 'publicPath']
  })
```

**Comment by faceyspacey** [comment]
nicely done!
